"""quote model

Revision ID: 14f8f3df1700
Revises: 
Create Date: 2018-08-31 01:27:02.487951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f8f3df1700'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('body', sa.String(length=250), nullable=False),
    sa.Column('by', sa.String(length=25), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_body'), 'quote', ['body'], unique=False)
    op.create_index(op.f('ix_quote_by'), 'quote', ['by'], unique=False)
    op.create_index(op.f('ix_quote_timestamp'), 'quote', ['timestamp'], unique=False)
    op.create_index(op.f('ix_quote_title'), 'quote', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_title'), table_name='quote')
    op.drop_index(op.f('ix_quote_timestamp'), table_name='quote')
    op.drop_index(op.f('ix_quote_by'), table_name='quote')
    op.drop_index(op.f('ix_quote_body'), table_name='quote')
    op.drop_table('quote')
    # ### end Alembic commands ###
